README
3.3 as recommended before won't actually work because of asyncserial, and the current most recent (3.6) won't work yet due to issue 62. Recommending 3.5 specifically might save people some time.
=> Specify Python version 3.5 specifically

misoc/targets/sayma_amc.py
LOCs were introduced to try to help with SDRAM issues on Sayma. AFAICT, there is no evidence they actually helped. SDRAM issues seem to have been fixed by other changes, so the LOCs are no longer needed.
Tested on HW at Oxford with Sayma AMC + RTM.
=> Sayma: remove unnecessary LOCs

misoc/cores/spi2.py
This patch adds support for SPI-over-LVDS for iCE40 platforms.
The logic is taken straight from the 7-Series differential interface, which produces a lot of code duplication. Refactoring would be great. Would for example differential tristate buffers as generic `Specials` be a good idea?
The `miso` buffer suffers the same problems as `DifferentialInput` discussed in m-labs/migen#178 with yosys/nextpnr getting confused if the `p` side of the differential pair is in the pcf.
Reviews most welcome. Thanks in advance!
=> spi2: add iCE40 differential interface

misoc/cores/lm32/core.py, misoc/cores/vexriscv/core.py
As proposed in [migen #201](https://github.com/m-labs/migen/pull/201) here's what needs to be done to remove `add_sources()` with an explicit list of files, which omitted files that are only referenced through `include` in Verilog.
In consequence, all files that are added through `add_source_dir()` occur in the output's `top.tcl`.
It also removes all verilog_include paths as the `include` directives only refer to files in the same source directory.
=> cores: replace use of add_sources(), remove use of add_verilog_include_path()

misoc/cores/liteeth_mini/phy/a7_1000basex.py, misoc/cores/liteeth_mini/phy/pcs_1000basex.py, misoc/test/test_pcs_1000basex.py
This pull request enables the existing 1000BASE-X PHY implementation to also support 10Mbps and 100Mbps via SGMII. This means the PHY can now automatically detect and operate in any of the following modes (tested on real testbench): 
* 1000Mbps, with 1000BASE-X transceiver
* 1000Mbps, with SGMII transceiver
* 100Mbps, with SGMII transceiver
* 10Mbps, with SGMII transceiver
For further explanation on the implementation, see the full commit message for c0cf664404b7abdbdb1a38e56bae34abdfdee50e.
=> liteeth: Add support for 10/100Mbps via SGMII

.gitmodules
Updated the submodules for llvm `libunwind` and `compiler_rt`. 
Worth noticing that the submodules are now pointing at an archived version of the two repositories.
The live versions have been merged into:
[llvm-new](https://github.com/llvm/llvm-project)
=> Updating submodules configuration after llvm changes

misoc/cores/liteeth_mini/phy/ku_1000basex.py
Fingers crossed, this PR should **finally, once and for all**, fix https://github.com/m-labs/artiq/issues/1424 where the Ethernet on the KU FPGA on Metlino would randomly break. The symptom can be any of the following:
* After replacing a working FPGA bitstream with another that only differs slightly (e.g. changing the ARTIQ version string in ROM, removing some unused EEM ports from the code), the new bitstream would cause the Ethernet to fail.
* After re-flashing with a new bitstream and reloading it to the FPGA, the Ethernet fails; after power-cycling, the Ethernet resumes to normal.
* After re-flashing with a new bitstream and reloading it to the FPGA, the Ethernet works normal; after power-cycling, the Ethernet fails.
* The Ethernet would randomly fail after each reloading (e.g. by …
=> liteeth: Fix Kintex UltraScale GTH intermittent breakage

misoc/integration/builder.py, misoc/software/bios/Makefile
This PR is to convert the generated `bios.bin` to big-endian.
A functioning gateware bitstream `top.bit` can be generated using `--integrated-rom-size` option (See #78).
However, booting at `0x400000` using `bios.bin` is not successful using `openocd` set in [artiq_flash](https://github.com/m-labs/artiq/blob/master/artiq/frontend/artiq_flash.py). Binary in big-endian is expected.
The little-endian binary of `bios.bin` is already converted into big-endian **in ~~ROM~~ `boot_data`** when building with `--integrated-rom-size` during memory initialization, in the following snippet:
https://github.com/m-labs/misoc/blob/dad351a66fbc8087a37bed0ce4b7bcf153e9795a/misoc/integration/builder.py#L171-L176
The `bios.bin` is flipped to big-endian when using a little-endian CPU (e.g. vexriscv).
The …
=> vexriscv: make bios big-endian

misoc/integration/cpu_interface.py
This patch enables the use of Clang to build VexRiscv target.
- Clang 9 is needed to build with RISC-V target
- Clang 10 is needed to build with C flag `-mcmodel=medany`
=> vexriscv: use clang

misoc/cores/vexriscv/core.py, misoc/software/include/base/csr-defs.h, misoc/software/libbase/system.c
This PR changes the VecRiscv core to `VecRiscv_IMA.v` in `VexRiscv-verilog` master to support atomic instructions (`lr`/`sc` & `amo`). (See [this PR](https://github.com/m-labs/VexRiscv-verilog/pull/10) in `VexRiscv-verilog`.)
- The `vexriscv/verilog` submodule is updated to include [this PR](https://github.com/m-labs/VexRiscv-verilog/pull/10).
- `vexriscv/core.py` now uses `VexRiscv_IMA.v`.
- Updated Machine IRQ Mask register and Machine IRQ Pending register defined in `csr-def.h`.
- Updated cache flushing instruction to `fence.i` and a custom instruction `.word(0x500F)`.
BIOS can be built and run using the updated VexRiscv core.
=> VexRiscv: Update to support atomic instructions

misoc/software/unwinder/src/UnwindRegistersRestore.S
This PR patches the breaking changes introduced to `unwinder` on the `or1k` platform. 
This modifies the register restoration order in `UnwindRegistersRestore.S`. The explanation can be found in #114 (after the merge).
=> unwinder: Fix resumption from unwinder for OR1K

misoc/cores/icap.py, misoc/targets/kasli.py, misoc/targets/kc705.py, misoc/targets/metlino.py
Added a new module that talks to ICAP. Only restart the gateware is implemented. Trigger the restart by writing a `1` to CSR ICAP iprog register.
Metlino and Kasli are supported at this time.
=> ICAP: talk to ICAP primitive to restart gateware

misoc/cores/liteeth_mini/mac/__init__.py, misoc/cores/liteeth_mini/mac/sram.py, misoc/cores/liteeth_mini/mac/wishbone.py, misoc/targets/afc3v1.py, misoc/targets/kasli.py, misoc/targets/kc705.py, misoc/targets/metlino.py, misoc/targets/mlabs_video.py, misoc/targets/sayma_amc.py, misoc/targets/simple.py
This patch adds Ethernet support to little endian targets (VexRiscv in particular).
- Added little endian support to EthMac (with reference to [LiteEth](https://github.com/enjoy-digital/liteeth/commit/ce72e34f56ba3356aa79f9de2e50ed59ec405135)), to applicable targets, i.e.
- `afc3v1.py`
- `kasli.py`
- `kc705.py`
- `metlino.py`
- `mlabs_video.py`
- `sayma_amc.py`
- `simple.py`
=> liteeth: Add little endian target support

misoc/cores/spi_flash.py, misoc/integration/builder.py, misoc/software/bios/Makefile, misoc/targets/afc3v1.py, misoc/targets/kasli.py, misoc/targets/kc705.py, misoc/targets/metlino.py, misoc/targets/papilio_pro.py, misoc/targets/pipistrello.py, misoc/targets/qm_xc6slx16_sdram.py, misoc/targets/sayma_amc.py
- Revert #111.
- Add little endian support to SPI flash ([reference from litex](https://github.com/enjoy-digital/litex/commit/468780c045da1222290bde69496852d5d3ee6e43#diff-dc7860dd5fd69b405989e6df5e77ef00695f8562b3590e6e5dc348aced2f3b3d)) for the following targets:
- afc3v1
- kasli
- kc705
- metlino
- papilio_pro
- pipistrello
- qm_xc6slx16_sdram (spi_flash seems broken there? It does not have the `dq` subsignal in the platform)
- sayma_amc
#111 byte-swaps the BIOS binary into little-endian, if the target CPU was configured with `vexriscv`.
Although it ensure the instructions read from SPI flash is with the correct endianness, configuring the flash becomes messy.
This can be demonstrated with reference to `artiq_mkfs`, suppose we have an entry of `{"foo": "1"}` in the flash with swapped …
=> spi_flash: Add little endian support

misoc/software/include/fdlibm/fdlibm.h
libm now uses the little endian version of macros in `fdlibm.h` (e.g. `__HI`, `__LO`) for RISC-V target.
=> (fd)libm: add RISC-V target to the list of little endian targets

misoc/integration/cpu_interface.py, misoc/integration/sdram_init.py, misoc/software/common.mak
The patch enables VexRiscv target to build in Rust using the builtin `riscv32imac-unknown-none-elf` target, while converting the built tools of VexRiscv from binutils to ld.lld and llvm-bintools. The purpose is to support the RISC-V port of ARTIQ.
- The triple is changed to `riscv32-unknown-linux` to emphasize that the CPU target is 32-bits RISC-V. The `linux` sys is specified to ensure that the `-shared` flag is implemented properly for compiling shared libraries (see ARTIQ).
- `CARGO_TRIPLE` and `CARGO_NORMAL` is now gated by the CPU type, only `or1k` and `vexriscv` will have both defined.
- The Rust builtin target `riscv32imac-unknown-none-elf` is supported when building with `vexriscv`, with the compression feature (`c`) disabled.
- The unstable flag `build-std=core,alloc` is added to …
=> VexRiscv: Add Rust, LLVM support

misoc/software/common.mak
- Updated Rust target triple to `riscv32ima-unknown-none-elf`, to match the changes in ARTIQ RISC-V.
- Build Rust library using `cargo xbuild` instead of `cargo rustc` with the unstable feature `build-std`
=> vexriscv: Build Rust library with cargo-xbuild

misoc/integration/soc_core.py
This patch is to revert the changes made to CSR address width calculation in 4f66420 for backward-compatibility.
4f66420 does automatic calculation of the required address width for the CSRs, assuming the CSR memory region always takes up 64KB.
However, some targets (e.g. [metlino in ARTIQ](https://github.com/m-labs/artiq/blob/master/artiq/gateware/targets/metlino.py)) needs a larger address space to support more CSR regions. Just as pre- 4f66420, assigning a larger `csr_address_width` can solve the issue.
If the effect of 4f66420 is desired, simply set `csr_address_width=13` when passing `cpu_bus_width=64` to `SoCCore`.
=> SoCCore: Re-expose CSR address width parameter

misoc/software/libunwind/Makefile
`LIBUNWIND_BUILD_ZERO_COST_APIS` was refined in RISC-V builds.
`LIBUNWIND_BUILD_ZERO_COST_APIS` is no longer defined in libunwind makefile for RISC-V targets.
=> libunwind: Suppress compilation warning

misoc/integration/cpu_interface.py
As discussed in https://git.m-labs.hk/M-Labs/artiq-zynq/pulls/176 - to prevent AXI bursts from being issued on CSR for Zynq-based systems, this adds ``dmb()`` calls for between memory accesses for registers bigger than 32 bits.
This patch adds this feature without breaking compatibility.
Unfortunately this needs to rely on ``libcortex_a9`` - cannot just call ``llvm_asm`` as that requires corresponding feature enabled in the crate (not file).
Few things come to mind now - since it's limited to only one platform, maybe CPU type should be also passed? Or the argument could be called ``use_cortexa9_dmb`` instead?
=> cpu_interface: add dmb() support
